<?php
/**
 * Created by PhpStorm.
 * User: nata
 * Date: 01.08.17
 * Time: 9:30
 */

/**
 * Implements hook_feeds_after_parse().
 */
function importer_feeds_after_parse(FeedsSource $source, FeedsParserResult $result) {

  if($source->id == 'product_importer') {

    // xpathparser:2 - price of product
    if ($result->items[0]['xpathparser:2'] == "Договорная") {
      $result->items[0]['xpathparser:2'] = 0;
    }
    else {
      $price = $result->items[0]['xpathparser:2'];
      $result->items[0]['xpathparser:2'] = str_replace(array(
        ',00 грн.',
        ','
      ), array('00', '.'), $price);
    }

    //xpathparser:4,5 - images of product
    if (is_array($result->items[0]['xpathparser:4'])) {
      $result->items[0]['xpathparser:5'] = $result->items[0]['xpathparser:4'];
      foreach ($result->items[0]['xpathparser:5'] as $key => $value) {
        $result->items[0]['xpathparser:5'][$key] = $result->items[0]['xpathparser:0'];
      }
    }
    else{
      $result->items[0]['xpathparser:5'] = $result->items[0]['xpathparser:0'];
    }

    //xpathparser:3 - avaliability of product
    if ($result->items[0]['xpathparser:3'] != "В наличии") {
      $result->items[0]['xpathparser:3'] = NULL;
    }

    $auto = $result->items[0]['xpathparser:6'];
    $auto = trim(str_replace('Запчасти ', '', $auto));
    $result->items[0]['xpathparser:6'] = $auto;
  }

  if($source->id == 'product_reference_importer') {
    $auto = $result->items[0]['xpathparser:4'];
    $auto = trim(str_replace('Запчасти ', '', $auto));
    $result->items[0]['xpathparser:4'] = $auto;

    $spare = $result->items[0]['xpathparser:5'];
    $auto = explode(" ", $auto);
    $new = array('', '');
    $spare = trim(str_replace($auto, $new, $spare));
    $result->items[0]['xpathparser:5'] = $spare;
  }

}

/**
 * Implements hook_feeds_presave().
 */
function importer_feeds_presave(FeedsSource $source, $entity, $item, $entity_id) {

  if ($source->id == "product_reference_importer"){
    if ($item['xpathparser:4'] == "Nissan Kubistar" || $item['xpathparser:4'] == "Renault Kangoo"){
      $entity->feeds_item->skip = TRUE;
    }
  }
  if($source->id == 'product_importer') {
    if ($item['xpathparser:6'] == "Nissan Kubistar" || $item['xpathparser:6'] == "Renault Kangoo"){
      $entity->feeds_item->skip = TRUE;
    }
  }
}